# SPDX-FileCopyrightText:  PyPSA-Earth and PyPSA-Eur Authors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: pypsa-earth
channels:
- conda-forge
- bioconda
- gurobi
dependencies:
- python>=3.8
- pip
- mamba   # esp for windows build

- pypsa>=0.24, <0.25
# - atlite>=0.2.4  # until https://github.com/PyPSA/atlite/issues/244 is not merged
- dask
- powerplantmatching>=0.5.7
- earth-osm>=2.1
- atlite

  # Dependencies of the workflow itself
- xlrd
- openpyxl
- seaborn
- snakemake-minimal<8
- memory_profiler
- ruamel.yaml<=0.17.26
- pytables
- lxml
- numpy
- pandas
- geopandas>=0.11.0
- fiona!=1.8.22
- xarray>=2023.11.0, <2023.12.0
- netcdf4
- networkx
- scipy
- pydoe2
- shapely>=2
- pre-commit
- pyomo
- matplotlib<=3.5.2
- reverse-geocode
- country_converter
- pyogrio
- numba
- py7zr

  # Keep in conda environment when calling ipython
- ipython
  # Jupyter notebook requirement
- ipykernel
- jupyterlab

  # GIS dependencies:
- cartopy
- descartes
- rasterio!=1.2.10
- rioxarray

 # Plotting
- geoviews
- hvplot
- graphviz
- contextily
- graphviz

  # PyPSA-Eur-Sec Dependencies
- geopy
- tqdm
- pytz
- country_converter

  # Cloud download
# - googledrivedownloader  # Commented until https://github.com/ndrplz/google-drive-downloader/pull/28 is merged: PR installed using pip

# Default solver for tests (required for CI)
- glpk
- ipopt<3.13.3
- gurobi=10.0.3

- pip:
  - git+https://github.com/davide-f/google-drive-downloader@master  # google drive with fix for virus scan
  - git+https://github.com/FRESNA/vresutils@master  # until new pip release > 0.3.1 (strictly)
  - tsam>=1.1.0
  - chaospy  # lastest version only available on pip
